apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  type: NodePort
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30008  # NodePort range: 30000-32767

